### ISSUE TITLE
There are 2 tray icons of WARP CLI and this GUI app

### ISSUE THREAD

**Issue by mirashif** [mrmoein/warp-cloudflare-gui#11]
![image](https://user-images.githubusercontent.com/34467318/168280228-6025de5d-79d4-4714-8d38-bda26aa85828.png)

**Comment by mrmoein** [comment]
this isuue fixed, pleas read isuue https://github.com/mrmoein/warp-cloudflare-gui/issues/9

**Comment by Den4enko** [comment]
This is not exactly the same problem as issue #9. It is a built-in indicator in warp-cli working on ubuntu. To turn it off, go to the autorun settings, and turn off "Cloudflare Zero-Trust"

**Comment by mrmoein** [comment]
Could you send the screenshot of tray icons options?

**Comment by Saiv46** [comment]
That's how it looks in autorun settings

![image](https://user-images.githubusercontent.com/47699394/174428179-4f60edc9-9f95-4cc0-87ad-094ba8b32a00.png)

**Comment by RichardRobertson** [comment]
I'd like to add to this for any other CachyOS users who might stumble upon it. You can permanently stop the original Cloudflare tray icon with

```
systemctl --user mask warp-taskbar
```
