### ISSUE TITLE
Wrong status on program start

### ISSUE THREAD

**Issue by maxyudin** [mrmoein/warp-cloudflare-gui#13]
WARP CLI is called with `enable-always-on`.

But on GUI start it says

> ### Connected
> Your internet is **not private**

Disconnecting and connecting again (doesn't matter using GUI or CLI) fixes the issue.

**Comment by smith558** [comment]
Same issue. WARP is running and connected yet the GUI says "Your internet is **not** private". The toggle is set correctly, however.

![image](https://user-images.githubusercontent.com/44023416/204368176-3c266c47-f92d-469f-b76e-346fb6966d30.png)

**Comment by mrmoein** [comment]
Fixed https://github.com/mrmoein/warp-cloudflare-gui/commit/3951f0dd7df464b3fd5b3e2a1a3723a9cee539c2
