### ISSUE TITLE
Tool doesnt Launch due to Improper .desktop-file-accessrights

### ISSUE THREAD

**Issue by Shadowphoenix** [mrmoein/warp-cloudflare-gui#3]
The Program will not boot from Applicationselector or latte-dock after a fresh install and even a complete wipe and reinstall. 
Upon snooping around in fileperms of all the scripts, out of all i found the .desktop that was created during install not to be marked as executable, changing that fixed the issue. 
Cant tell if this is an issue specific to my system or with the scripts, but im mentioning it here if others encounter the same problem.

**Comment by mrmoein** [comment]
Thanks, I added it to the installation steps
