### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by rrebollo** [mrmoein/warp-cloudflare-gui#4]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

Kernel: 4.19.0-19-amd64 x86_64 bits: 64 Desktop: Cinnamon 5.0.7 Distro: LMDE 4 Debbie

**Comment by rrebollo** [comment]
Solution found in a qt forum:
[coffeesmoke](https://forum.qt.io/user/coffeesmoke) [Nov 23, 2020, 2:46 AM](https://forum.qt.io/post/628694)

So, Debian 10:

    ldd -r <for example, home dir>/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/libqxcb.so | grep libxcb-util

libxcb-util.so.1 => not found

    Ok, continue...
    sudo find /usr/lib | grep libxcb-util
    ...
    libxcb-util.so.0.0.0
    libxcb-util.so.0.0
    libxcb-util.so.0
    , but need
    libxcb-util.so.1

    Ok, Debian... :) Redy?
    sudo ln -fs /usr/lib/x86_64-linux-gnu/libxcb-util.so.0.0.0 /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0
    sudo ln -fs /usr/lib/x86_64-linux-gnu/libxcb-util.so.0.0.0 /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0
    sudo ln -fs /usr/lib/x86_64-linux-gnu/libxcb-util.so.0.0.0 /usr/lib/x86_64-linux-gnu/libxcb-util.so.1

**Comment by LegendaryBob13** [comment]
For anyone running into a similar issue I found that simply running `sudo apt-get install --reinstall libxcb-xinerama0` fixes the problem :smile:

**Comment by S4adam** [comment]
@LegendaryBob13 Thanks, it worked on Ubuntu 20.04
