### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Xnuvers007** [mrmoein/warp-cloudflare-gui#5]
![image](https://user-images.githubusercontent.com/62522733/162527242-e62e862b-93d8-484b-ae16-ec3b2a264262.png)

i activate but the status still disconnected

**Comment by mrmoein** [comment]
Hello can you run it in terminal and let me know the output?

And also are you update the app to the latest version?

**Comment by Xnuvers007** [comment]
> Hello can you run it in terminal and let me know the output?
> 
> And also are you update the app to the latest version?
> 
> Can you connect with `$ warp-cli connect`?

Warp Cli not found 
![image](https://user-images.githubusercontent.com/62522733/163737884-d0487388-4635-42d9-b69c-47b3e7cde539.png)

**Comment by mrmoein** [comment]
First of all you must install `warp-cli`!

Go to https://developers.cloudflare.com/warp-client/get-started/linux/
And install it
Then run `warp-cli register` , now your app will work

**Comment by mrmoein** [comment]
In future Im gona add some errors for missing warp-cli command
